version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - violetagg
  target-branch: "1.2.x"
  labels:
  - type/dependency-upgrade
  ignore:
  # Don't update Micrometer
  - dependency-name: io.micrometer:micrometer-core
    versions:
    - "> 1.14.0"
  # Don't update Micrometer Tracing
  - dependency-name: io.micrometer:micrometer-tracing
    versions:
    - "> 1.4.0"
  - dependency-name: io.micrometer:micrometer-tracing-integration-test
    versions:
    - "> 1.4.0"
  - dependency-name: io.micrometer:micrometer-tracing-bridge-brave
    versions:
    - "> 1.4.0"
  # Don't update Context Propagation
  - dependency-name: io.micrometer:context-propagation
    versions:
    - "> 1.1.0"
  # Versions > 9 require JDK11+
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-core
    versions:
    - ">= 10.0.a"
  # Versions > 6.13 require JDK11+
  - dependency-name: com.diffplug.spotless
    versions:
    - "[6.14.a, 8]"
  # Versions > 6 require JDK17+
  - dependency-name: biz.aQute.bnd.builder
    versions:
    - "[7.a, 8]"
  # Versions > 4 require JDK11+
  - dependency-name: org.jfrog.buildinfo:build-info-extractor-gradle
    versions:
    - "[5.a, 7]"
  # Versions > 4 require JDK11+
  - dependency-name: org.mockito:mockito-core
    versions:
    - "[5.a, 6]"
  # Versions > 0.9.25 require JDK11+
  - dependency-name: org.graalvm.buildtools.native
    versions:
    - "[0.9.25, 0.12]"
  - dependency-name: ch.qos.logback:logback-classic
    versions:
    - "[1.3.a, 1.6]"
  - dependency-name: org.slf4j:*
    versions:
    - "[2.a, 3]"
  # Versions > 0.19.1 require JDK11+
  - dependency-name: io.specto:hoverfly-java-junit5
    versions:
    - "[0.20.a, 1]"
  # Versions > 8 require JDK11+
  - dependency-name: com.gradleup.shadow
    versions:
    - "[9.a, 10]"
  rebase-strategy: disabled
- package-ecosystem: github-actions
  directory: "/"
  schedule:
      interval: daily
  open-pull-requests-limit: 10
  assignees:
      - violetagg
  target-branch: "1.2.x"
  labels:
      - type/dependency-upgrade
  rebase-strategy: disabled
- package-ecosystem: npm
  directory: /docs
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
    - violetagg
  target-branch: "1.2.x"
  labels:
    - type/dependency-upgrade
  rebase-strategy: disabled
